# fly.toml app configuration file generated for bot-whats-floral-bush-6936 on 2025-03-14T00:30:20-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-whats-floral-bush-6936'
primary_region = 'gig'

[build]

[deploy]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2


[deploy]
replicas = 3  # Ajuste o número de réplicas conforme necessário
